# Generated by Django 6.0 on 2026-01-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('f_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('f_number', models.IntegerField(blank=True, null=True)),
                ('f_password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
