# Generated by Django 6.0 on 2026-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeds_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seeds_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seeds_quantity', models.IntegerField(blank=True, null=True)),
                ('seeds_price', models.IntegerField(blank=True, null=True)),
                ('seeds_image', models.ImageField(blank=True, null=True, upload_to='Seeds_Image')),
                ('seeds_description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
