# Generated by Django 6.0 on 2026-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_seeds_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farming_Tools_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_quantity', models.IntegerField(blank=True, null=True)),
                ('tool_price', models.IntegerField(blank=True, null=True)),
                ('tool_image', models.ImageField(blank=True, null=True, upload_to='Tools_image')),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
