# Generated by Django 6.0 on 2026-01-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_farming_tools_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming_tools_db',
            name='tool_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
